# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/taller_nbdev_2025',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/taller_nbdev_2025',
                'lib_path': 'taller_nbdev_2025'},
  'syms': {'taller_nbdev_2025.core': {'taller_nbdev_2025.core.foo': ('core.html#foo', 'taller_nbdev_2025/core.py')}}}
